language: node_js
dist: trusty
node_js:
  - "10"

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

install:
  - npm install

script:
  - ./node_modules/.bin/eslint wc.js
  - ./node_modules/karma/bin/karma start --single-run

addons:
  chrome: stable