language: node_js
os: osx
node_js:
    - "10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
    - npm install

script:
    - ./node_modules/.bin/eslint wc.js
    - ./node_modules/karma/bin/karma start --single-run
